name: financia_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.3
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/logo_sin_nombre.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/

flutter_intl:
  enabled: true
